export type SiloLink = {
  href: string;
  label: string;
  text?: string;
  eyebrow?: string;
};

export type ProofCaseLinkSet = {
  client: string;
  campaign: string;
  category: string;
  links: readonly SiloLink[];
};

export const frSiloLinks = {
  expertisesHub: [
    { href: "/expertises/strategie-digitale", label: "Stratégie digitale", text: "Structurer l’audit, la data, le média, le CRM et les priorités business." },
    { href: "/expertises/achat-media", label: "Achat média", text: "Piloter Google Ads, Meta Ads, tracking et campagnes de performance." },
    { href: "/expertises/referencement-seo", label: "SEO / GEO", text: "Renforcer la visibilité Google et les réponses des moteurs IA." },
    { href: "/expertises/ia-automation", label: "IA & automation", text: "Relier CRM, WhatsApp, scoring et workflows commerciaux." },
    { href: "/secteurs", label: "Secteurs accompagnés", text: "Adapter les leviers aux enjeux éducation, retail, FMCG, auto et tourisme." },
    { href: "/realisations", label: "Réalisations", text: "Voir les dispositifs activés pour des marques au Maroc et à l’international." },
  ],
  strategy: [
    { href: "/expertises/achat-media", label: "Achat média", text: "Transformer la stratégie en plan d’acquisition mesurable." },
    { href: "/expertises/referencement-seo", label: "SEO / GEO", text: "Installer une visibilité organique durable autour des intentions clés." },
    { href: "/expertises/ia-automation", label: "IA & automation", text: "Automatiser les relances, les dashboards et les workflows CRM." },
    { href: "/secteurs", label: "Secteurs", text: "Décliner la feuille de route selon votre marché." },
  ],
  media: [
    { href: "/publicite-en-ligne-maroc", label: "Publicité en ligne au Maroc", text: "Landing nationale pour cadrer Google Ads, Meta Ads, TikTok, display, tracking et reporting." },
    { href: "/expertises/strategie-digitale", label: "Stratégie digitale", text: "Cadrer les objectifs, audiences, budgets et indicateurs." },
    { href: "/expertises/achat-media", label: "Paid social & achat média", text: "Transformer Meta, TikTok et LinkedIn en leviers de leads et de ventes." },
    { href: "/expertises/google-ads-maroc", label: "Google Ads Maroc", text: "Capter les intentions actives avec Search, PMax, tracking et landing pages." },
    { href: "/expertises/meta-ads-maroc", label: "Meta Ads Maroc", text: "Relier Facebook, Instagram, créatifs, Pixel, CAPI et CRM." },
    { href: "/expertises/tiktok-ads-maroc", label: "TikTok Ads Maroc", text: "Tester des contenus natifs, Spark Ads, UGC et retargeting." },
    { href: "/expertises/generation-leads-maroc", label: "Génération de leads Maroc", text: "Connecter trafic, landing pages, WhatsApp, CRM et qualification." },
    { href: "/insights/cout-campagne-google-ads-maroc", label: "Prix campagne Google Ads Maroc", text: "Comprendre budget média, honoraires, tracking et coûts par secteur." },
    { href: "/expertises/referencement-seo", label: "SEO / GEO", text: "Compléter le média paid par un socle organique." },
    { href: "/expertises/ia-automation", label: "IA & automation", text: "Relier leads, scoring, WhatsApp et reporting." },
    { href: "/realisations", label: "Réalisations média", text: "Parcourir les campagnes et résultats visibles." },
  ],
  seo: [
    { href: "/agence-seo-maroc", label: "Agence SEO au Maroc", text: "Approche agence pour audit, SEO local, reporting et croissance organique au Maroc." },
    { href: "/expertises/strategie-digitale", label: "Stratégie digitale", text: "Aligner SEO, GEO, contenu et acquisition." },
    { href: "/agence", label: "Agence digitale Casablanca", text: "Relier référencement, marque, acquisition et preuve locale." },
    { href: "/expertises/web-si", label: "Web & SI", text: "Optimiser les socles techniques et les parcours." },
    { href: "/expertises/brand-content", label: "Brand content", text: "Créer les contenus qui répondent aux intentions de recherche." },
    { href: "/secteurs", label: "Pages secteurs", text: "Décliner les cas clients, chiffres, preuves et FAQ par marché." },
    { href: "/insights", label: "Insights", text: "Lire les analyses sur la visibilité et la performance." },
  ],
  socialAds: [
    { href: "/expertises/achat-media", label: "Achat média", text: "Connecter Social Ads, search, programmatique et budget pacing." },
    { href: "/insights/campagnes-meta-2026-bonnes-pratiques", label: "Campagnes Meta 2026", text: "Lire les bonnes pratiques créatives et média pour Meta Ads." },
    { href: "/insights/cout-campagne-google-ads-maroc", label: "Prix campagne Google Ads Maroc", text: "Comparer budget média, tracking, landing pages et pilotage." },
    { href: "/secteurs/retail-ecommerce", label: "Retail & e-commerce", text: "Activer social commerce, trafic magasin, retargeting et CRM." },
    { href: "/secteurs/education", label: "Éducation", text: "Générer des leads admissions avec Meta, TikTok et retargeting." },
    { href: "/realisations", label: "Réalisations", text: "Voir les campagnes et preuves déjà produites par Richmedia." },
  ],
  content: [
    { href: "/expertises/influence", label: "Campagne influence", text: "Amplifier un contenu social-first avec les bons créateurs UGC." },
    { href: "/expertises/evenementiel", label: "Activation de marque", text: "Transformer un temps fort en contenu de marque exploitable." },
    { href: "/insights/createurs-marques-collaborations-durables", label: "Créateurs UGC", text: "Comprendre comment construire des collaborations durables avec les créateurs." },
    { href: "/secteurs/fmcg", label: "Brand content Maroc pour FMCG", text: "Adapter KV, UGC, lancement produit et campagnes retail aux marques FMCG." },
    { href: "/secteurs/gms", label: "Contenu social-first pour GMS", text: "Créer des prises de parole visibles pour promotions, catalogues et activation magasin." },
    { href: "/realisations", label: "Réalisations brand content Maroc", text: "Voir les campagnes créatives, sociales et activations de marque déjà produites." },
    { href: "/contact", label: "Créer une activation de marque", text: "Cadrer une campagne brand content, influence ou UGC avec Richmedia." },
  ],
  conversion: [
    { href: "/expertises/whatsapp-marketing-maroc", label: "WhatsApp Marketing Maroc", text: "Structurer opt-in, templates, scénarios, CRM et reporting conversationnel." },
    { href: "/expertises/marketing-automation-crm-maroc", label: "Marketing Automation & CRM", text: "Relier capture, scoring, routing, relances et conversion commerciale." },
    { href: "/produits/whatsapp", label: "WhatsApp Business Maroc", text: "Activer conversations, notifications, relances et conversion WhatsApp." },
    { href: "/insights/whatsapp-business-canal-conversion", label: "Conversion WhatsApp", text: "Comprendre comment WhatsApp devient un canal de qualification et de vente." },
    { href: "/insights/crm-automation-aligner-marketing-sales", label: "CRM marketing", text: "Aligner marketing, sales, lead nurturing, scoring et reporting commercial." },
    { href: "/secteurs/automobile", label: "Lead nurturing automobile", text: "Qualifier les demandes d’essai avec automation IA et WhatsApp Business Maroc." },
    { href: "/secteurs/retail-ecommerce", label: "Automation IA retail", text: "Relancer clients, coupons, paniers et trafic magasin avec des scénarios CRM." },
    { href: "/secteurs/gms", label: "CRM marketing GMS", text: "Connecter promotions, audiences, coupons, WhatsApp et mesure." },
    { href: "/contact", label: "Démarrer une automation IA", text: "Cadrer vos workflows, triggers et scénarios de conversion." },
  ],
  web: [
    { href: "/creation-site-web-maroc", label: "Création de site web au Maroc", text: "Landing nationale pour cadrer UX/UI, design, développement, SEO, performance et conversion." },
    { href: "/expertises/referencement-seo", label: "SEO / GEO", text: "Construire des pages visibles, rapides et indexables." },
    { href: "/expertises/ia-automation", label: "IA & automation", text: "Brancher le site aux outils métier et CRM." },
    { href: "/expertises/strategie-digitale", label: "Stratégie digitale", text: "Prioriser les parcours et les contenus à créer." },
    { href: "/produits/hypeo", label: "Hypeo", text: "Découvrir un produit orienté performance et activation." },
  ],
  influence: [
    { href: "/gestion-reseaux-sociaux-maroc", label: "Gestion des réseaux sociaux au Maroc", text: "Piloter stratégie éditoriale, contenus, community management, modération et reporting." },
    { href: "/marketing-influence-maroc", label: "Marketing d’influence au Maroc", text: "Comprendre l’approche marché : créateurs, micro/nano, UGC, villes et amplification." },
    { href: "/expertises/influence", label: "Social, Influence & UGC", text: "Page service pour casting créateurs, UGC, briefs et pilotage de campagne." },
    { href: "/expertises/influence-marketing-maroc", label: "Influence Marketing Maroc", text: "Structurer casting, brief, UGC, amplification paid et mesure." },
    { href: "/expertises/social-media-maroc", label: "Social Media Maroc", text: "Relier stratégie éditoriale, community management, contenus et performance." },
    { href: "/expertises/social-listening-maroc", label: "Social Listening Maroc", text: "Transformer conversations, réputation et tendances en décisions." },
    { href: "/expertises/brand-content", label: "Brand content Maroc", text: "Transformer les messages de marque en contenus activables et social-first." },
    { href: "/expertises/achat-media", label: "Achat média", text: "Amplifier les contenus créateurs en social ads." },
    { href: "/insights/createurs-marques-collaborations-durables", label: "Créateurs UGC", text: "Structurer des collaborations créateurs utiles et durables." },
    { href: "/secteurs/fmcg", label: "FMCG", text: "Adapter la campagne influence aux lancements, retail et promotions." },
    { href: "/realisations", label: "Réalisations", text: "Voir des campagnes de marque et d’engagement." },
  ],
  phygital: [
    { href: "/expertises/geofencing-drive-to-store-maroc", label: "Géofencing & drive-to-store", text: "Relier zone de chalandise, audiences locales, contenu et trafic magasin." },
    { href: "/expertises/achat-media", label: "Achat média", text: "Générer trafic, visites et conversions magasin." },
    { href: "/expertises/ia-automation", label: "IA & automation", text: "Relier QR, WhatsApp, CRM et coupons." },
    { href: "/secteurs/retail-ecommerce", label: "Retail & e-commerce", text: "Connecter drive-to-store, social commerce et vente." },
    { href: "/contact", label: "Cadrer une activation", text: "Passer d’une idée terrain à un dispositif pilotable." },
  ],
  event: [
    { href: "/expertises/brand-content", label: "Brand content Maroc", text: "Transformer les temps forts en contenu social-first et preuves de marque." },
    { href: "/expertises/influence", label: "Campagne influence", text: "Inviter les bons relais et amplifier l’événement avec créateurs UGC." },
    { href: "/expertises/achat-media", label: "Achat média", text: "Soutenir inscriptions, trafic et retombées." },
    { href: "/secteurs/institutionnel", label: "Institutionnel", text: "Adapter le dispositif aux enjeux publics et pédagogiques." },
  ],
  sectorsHub: [
    { href: "/secteurs/education", label: "Éducation", text: "Admissions, leads, landing pages et campagnes médias." },
    { href: "/secteurs/immobilier", label: "Immobilier", text: "Leads qualifiés, landing pages projet, SEO local et CRM commercial." },
    { href: "/secteurs/retail-ecommerce", label: "Retail & e-commerce", text: "Acquisition, social commerce, trafic magasin et CRM." },
    { href: "/secteurs/gms", label: "GMS", text: "Promotions, catalogues digitaux, couponing, retail media et reporting." },
    { href: "/secteurs/institutionnel", label: "Institutionnel", text: "Campagnes publiques, pédagogie, contenus, SEO/GEO et plateformes web." },
    { href: "/secteurs/tourisme-hotellerie", label: "Tourisme / hôtellerie", text: "SEO destination, réservation, contenus immersifs et influence travel." },
    { href: "/secteurs/automobile", label: "Automobile", text: "Leads qualifiés, essais, showroom, WhatsApp et reporting." },
    { href: "/secteurs/fmcg", label: "FMCG", text: "Brand content, activation retail, influence et lancement produit." },
  ],
  casesHub: [
    { href: "/expertises/brand-content", label: "Brand content", text: "Créer des campagnes visibles et mémorisables." },
    { href: "/expertises/achat-media", label: "Achat média", text: "Booster visibilité, impressions, ouvertures et engagement." },
    { href: "/expertises/ia-automation", label: "Automation IA", text: "Relier activation, WhatsApp Business Maroc, CRM marketing et mesure." },
    { href: "/secteurs/fmcg", label: "FMCG", text: "Explorer les campagnes produits et retail." },
    { href: "/secteurs/automobile", label: "Automobile", text: "Voir les logiques de génération de leads et d’essais." },
    { href: "/contact", label: "Créer un cas client", text: "Définir le format, les KPI et le dispositif." },
  ],
  articleBusiness: [
    { href: "/expertises/ia-automation", label: "Automation IA", text: "Relier CRM marketing, lead nurturing et conversion." },
    { href: "/produits/whatsapp", label: "WhatsApp Business Maroc", text: "Activer la conversion WhatsApp et les relances." },
    { href: "/expertises/brand-content", label: "Brand content Maroc", text: "Transformer l’insight en contenu social-first activable." },
    { href: "/expertises/achat-media", label: "Paid social & achat média", text: "Amplifier les contenus et convertir les audiences sociales." },
    { href: "/expertises/referencement-seo", label: "SEO / GEO", text: "Structurer la visibilité organique." },
    { href: "/contact", label: "Parler à un expert", text: "Relier le sujet à votre contexte business." },
  ],
} satisfies Record<string, readonly SiloLink[]>;

export const enSiloLinks = {
  expertisesHub: [
    { href: "/en/expertises/strategie-digitale", label: "Digital strategy", text: "Structure audit, data, media, CRM and business priorities." },
    { href: "/en/expertises/achat-media", label: "Media buying", text: "Manage Google Ads, Meta Ads, tracking and performance campaigns." },
    { href: "/en/expertises/seo-geo", label: "SEO / GEO", text: "Improve visibility on Google and AI answer engines." },
    { href: "/en/expertises/ia-automation", label: "AI & automation", text: "Connect CRM, WhatsApp, scoring and commercial workflows." },
    { href: "/en/sectors", label: "Industries", text: "Adapt levers to education, retail, FMCG, automotive and tourism." },
    { href: "/en/case-studies", label: "Case studies", text: "Explore campaigns activated for brands in Morocco and abroad." },
  ],
  strategy: [
    { href: "/en/expertises/achat-media", label: "Media buying", text: "Turn strategy into a measurable acquisition plan." },
    { href: "/en/expertises/seo-geo", label: "SEO / GEO", text: "Build durable organic visibility around priority intents." },
    { href: "/en/expertises/ia-automation", label: "AI & automation", text: "Automate follow-ups, dashboards and CRM workflows." },
    { href: "/en/sectors", label: "Industries", text: "Adapt the roadmap to your market." },
  ],
  media: [
    { href: "/online-advertising-morocco", label: "Online Advertising Morocco", text: "National landing for Google Ads, Meta Ads, TikTok, display, tracking and reporting." },
    { href: "/en/expertises/strategie-digitale", label: "Digital strategy", text: "Frame objectives, audiences, budgets and KPIs." },
    { href: "/en/expertises/achat-media", label: "Paid social & media buying", text: "Turn Meta, TikTok and LinkedIn into lead and sales levers." },
    { href: "/en/insights/google-ads-campaign-cost-morocco", label: "Google Ads campaign cost in Morocco", text: "Understand media budget, fees, tracking and sector cost factors." },
    { href: "/en/expertises/seo-geo", label: "SEO / GEO", text: "Support paid media with a strong organic base." },
    { href: "/en/expertises/ia-automation", label: "AI & automation", text: "Connect leads, scoring, WhatsApp and reporting." },
    { href: "/en/case-studies", label: "Media case studies", text: "Browse campaigns and visible results." },
  ],
  seo: [
    { href: "/seo-agency-morocco", label: "SEO Agency Morocco", text: "Agency approach for audits, local SEO, reporting and organic growth in Morocco." },
    { href: "/en/expertises/strategie-digitale", label: "Digital strategy", text: "Align SEO, GEO, content and acquisition." },
    { href: "/en/agency", label: "Digital agency in Casablanca", text: "Connect search, brand, acquisition and local proof." },
    { href: "/en/expertises/web-si", label: "Web & systems", text: "Optimize technical foundations and user journeys." },
    { href: "/en/expertises/brand-content", label: "Brand content", text: "Create content that answers search intent." },
    { href: "/en/sectors", label: "Sector pages", text: "Document client cases, figures, proof and FAQs by market." },
    { href: "/en/insights", label: "Insights", text: "Read analysis on visibility and performance." },
  ],
  socialAds: [
    { href: "/en/expertises/achat-media", label: "Media buying", text: "Connect Social Ads, search, programmatic and budget pacing." },
    { href: "/en/insights/meta-campaigns-2026-best-practices", label: "Meta campaigns 2026", text: "Read creative and media best practices for Meta Ads." },
    { href: "/en/insights/google-ads-campaign-cost-morocco", label: "Google Ads cost in Morocco", text: "Compare media budget, tracking, landing pages and management." },
    { href: "/en/sectors/retail-ecommerce", label: "Retail & e-commerce", text: "Activate social commerce, store traffic, retargeting and CRM." },
    { href: "/en/sectors/education", label: "Education", text: "Generate admissions leads with Meta, TikTok and retargeting." },
    { href: "/en/case-studies", label: "Case studies", text: "See campaigns and proof already produced by Richmedia." },
  ],
  content: [
    { href: "/en/expertises/influence", label: "Influence campaign", text: "Amplify social-first content with the right UGC creators." },
    { href: "/en/expertises/evenementiel", label: "Brand activation", text: "Turn a key moment into reusable brand content." },
    { href: "/en/insights/creators-brands-durable-collaborations", label: "UGC creators", text: "Understand how to build durable creator collaborations." },
    { href: "/en/sectors/fmcg", label: "Brand content in Morocco for FMCG", text: "Adapt key visuals, UGC, launches and retail campaigns for FMCG brands." },
    { href: "/en/sectors/grocery-retail", label: "Social-first content for grocery retail", text: "Create visible narratives for promotions, catalogues and in-store activation." },
    { href: "/en/case-studies", label: "Richmedia brand content case studies", text: "See creative, social and brand activation campaigns already produced." },
    { href: "/en/contact", label: "Create a brand activation", text: "Frame a brand content, influence or UGC campaign with Richmedia." },
  ],
  conversion: [
    { href: "/en/products/whatsapp", label: "WhatsApp Business Morocco", text: "Activate conversations, notifications, reminders and WhatsApp conversion." },
    { href: "/en/insights/whatsapp-business-conversion-channel", label: "WhatsApp conversion", text: "Understand how WhatsApp becomes a qualification and sales channel." },
    { href: "/en/insights/crm-automation-marketing-sales-alignment", label: "Marketing CRM", text: "Align marketing, sales, lead nurturing, scoring and commercial reporting." },
    { href: "/en/sectors/automotive", label: "Automotive lead nurturing", text: "Qualify test-drive requests with AI automation and WhatsApp Business Morocco." },
    { href: "/en/sectors/retail-ecommerce", label: "Retail AI automation", text: "Follow up customers, coupons, carts and store traffic with CRM scenarios." },
    { href: "/en/sectors/grocery-retail", label: "Grocery retail marketing CRM", text: "Connect promotions, audiences, coupons, WhatsApp and measurement." },
    { href: "/en/contact", label: "Start an AI automation", text: "Frame workflows, triggers and conversion scenarios." },
  ],
  web: [
    { href: "/website-development-morocco", label: "Website Development Morocco", text: "National landing for UX/UI, web design, development, SEO, performance and conversion." },
    { href: "/en/expertises/seo-geo", label: "SEO / GEO", text: "Build fast, indexable and visible pages." },
    { href: "/en/expertises/ia-automation", label: "AI & automation", text: "Connect the website to business tools and CRM." },
    { href: "/en/expertises/strategie-digitale", label: "Digital strategy", text: "Prioritize journeys and content to produce." },
    { href: "/en/products/hypeo", label: "Hypeo", text: "Discover a performance and activation product." },
  ],
  influence: [
    { href: "/social-media-management-morocco", label: "Social media management in Morocco", text: "Manage editorial strategy, content, community management, moderation and reporting." },
    { href: "/influencer-marketing-morocco", label: "Influencer marketing in Morocco", text: "Understand the market approach: creators, micro/nano, UGC, local cities and amplification." },
    { href: "/en/expertises/influence", label: "Social, Influence & UGC", text: "Service page for creator selection, UGC, briefs and campaign management." },
    { href: "/en/expertises/brand-content", label: "Brand content in Morocco", text: "Turn brand messages into activatable social-first content." },
    { href: "/en/expertises/achat-media", label: "Media buying", text: "Amplify creator content through social ads." },
    { href: "/en/insights/creators-brands-durable-collaborations", label: "UGC creators", text: "Structure useful and durable creator collaborations." },
    { href: "/en/sectors/fmcg", label: "FMCG", text: "Adapt influence campaigns to launches, retail and promotions." },
    { href: "/en/case-studies", label: "Case studies", text: "See brand and engagement campaigns." },
  ],
  phygital: [
    { href: "/en/expertises/achat-media", label: "Media buying", text: "Generate traffic, visits and store conversions." },
    { href: "/en/expertises/ia-automation", label: "AI & automation", text: "Connect QR, WhatsApp, CRM and coupons." },
    { href: "/en/sectors/retail-ecommerce", label: "Retail & e-commerce", text: "Link drive-to-store, social commerce and sales." },
    { href: "/en/contact", label: "Frame an activation", text: "Move from field idea to measurable system." },
  ],
  event: [
    { href: "/en/expertises/brand-content", label: "Brand content in Morocco", text: "Turn key moments into social-first content and brand proof." },
    { href: "/en/expertises/influence", label: "Influence campaign", text: "Invite the right relays and amplify the event with UGC creators." },
    { href: "/en/expertises/achat-media", label: "Media buying", text: "Support registrations, traffic and reach." },
    { href: "/en/sectors/institutional", label: "Institutional", text: "Adapt the setup to public and educational goals." },
  ],
  sectorsHub: [
    { href: "/en/sectors/education", label: "Education", text: "Admissions, leads, landing pages and media campaigns." },
    { href: "/en/sectors/real-estate", label: "Real estate", text: "Qualified leads, project landing pages, local SEO and commercial CRM." },
    { href: "/en/sectors/retail-ecommerce", label: "Retail & e-commerce", text: "Acquisition, social commerce, store traffic and CRM." },
    { href: "/en/sectors/grocery-retail", label: "Grocery retail", text: "Promotions, digital catalogues, couponing, retail media and reporting." },
    { href: "/en/sectors/institutional", label: "Institutional", text: "Public campaigns, education, content, SEO/GEO and web platforms." },
    { href: "/en/sectors/tourism-hospitality", label: "Tourism / hospitality", text: "Destination SEO, booking, immersive content and travel influence." },
    { href: "/en/sectors/automotive", label: "Automotive", text: "Qualified leads, test drives, showroom, WhatsApp and reporting." },
    { href: "/en/sectors/fmcg", label: "FMCG", text: "Brand content, retail activation, influence and launches." },
  ],
  casesHub: [
    { href: "/en/case-studies/model-case-study", label: "Digital marketing case study format", text: "See the structure used to document context, system and results." },
    { href: "/en/case-studies/uir-acquisition-campaign-2023-2024", label: "Richmedia UIR acquisition case study", text: "Open a complete education growth system." },
    { href: "/en/expertises/brand-content", label: "Richmedia case study", text: "Connect proof to brand content and creative campaigns." },
    { href: "/en/expertises/achat-media", label: "Digital campaign in Morocco", text: "Connect proof to media buying and performance." },
    { href: "/en/expertises/ia-automation", label: "Growth system", text: "Connect proof to WhatsApp, CRM and measurement." },
    { href: "/en/contact", label: "Create a growth system", text: "Move from proof to a new campaign brief." },
  ],
  articleBusiness: [
    { href: "/en/expertises/ia-automation", label: "AI automation", text: "Connect marketing CRM, lead nurturing and conversion." },
    { href: "/en/products/whatsapp", label: "WhatsApp Business Morocco", text: "Activate WhatsApp conversion and follow-ups." },
    { href: "/en/expertises/brand-content", label: "Brand content in Morocco", text: "Turn the insight into social-first content." },
    { href: "/en/expertises/achat-media", label: "Paid social & media buying", text: "Amplify content and convert social audiences." },
    { href: "/en/expertises/seo-geo", label: "SEO / GEO", text: "Structure organic visibility." },
    { href: "/en/case-studies", label: "Richmedia case studies", text: "Move from article to proof and business results." },
    { href: "/en/contact", label: "Talk to an expert", text: "Connect the topic to your business context." },
  ],
} satisfies Record<string, readonly SiloLink[]>;

export const sectorSiloLinksFr = {
  education: [
    { href: "/expertises/achat-media", label: "Acquisition admissions", text: "Générer des leads qualifiés pour écoles et universités." },
    { href: "/expertises/referencement-seo", label: "SEO éducation", text: "Capter les recherches formation, concours et admission." },
    { href: "/expertises/ia-automation", label: "WhatsApp & CRM", text: "Relancer les prospects et suivre les inscriptions." },
    { href: "/expertises/web-si", label: "Landing pages admissions", text: "Créer des parcours mobiles rapides pour transformer les demandes." },
    { href: "/expertises/brand-content", label: "Contenus preuve", text: "Rassurer étudiants et parents avec des contenus utiles." },
    { href: "/realisations/uir-campagne-acquisition-2023-2024", label: "Case study UIR acquisition", text: "Voir une campagne admissions full-funnel." },
    { href: "/realisations/universite-euromed-refonte-site-web-2025", label: "Case study Euromed Drupal", text: "Voir une refonte web éducation multilingue." },
    { href: "/realisations/tbs-master-acquisition-2025", label: "Case study TBS Master", text: "Voir une campagne d’acquisition Master multicanale." },
  ],
  immobilier: [
    { href: "/expertises/achat-media", label: "Leads immobiliers", text: "Acquérir des demandes qualifiées pour projets et visites." },
    { href: "/expertises/web-si", label: "Landing pages projet", text: "Créer des parcours clairs pour convertir les demandes." },
    { href: "/expertises/referencement-seo", label: "SEO local", text: "Travailler les requêtes résidence, ville et quartier." },
    { href: "/expertises/ia-automation", label: "CRM & reporting", text: "Suivre les leads jusqu’à la visite commerciale." },
    { href: "/expertises/strategie-digitale", label: "Stratégie digitale immobilière", text: "Cadrer audiences, preuves, canaux et saisonnalité commerciale." },
    { href: "/realisations/prestigia-riad-al-andalous-acquisition-2026", label: "Case study Prestigia", text: "Voir une campagne d’acquisition immobilière premium." },
    { href: "/realisations#ryad-al-andalous-rabat", label: "Réalisation Ryad Al Andalous", text: "Voir une référence immobilière premium." },
    { href: "/realisations#rabat-riviera-golf-living", label: "Réalisation Rabat Riviera", text: "Voir une campagne immobilier et lifestyle." },
  ],
  "retail-ecommerce": [
    { href: "/expertises/achat-media", label: "Drive-to-store", text: "Générer trafic, ventes et visites magasin." },
    { href: "/expertises/brand-content", label: "Social commerce", text: "Produire les contenus qui déclenchent l’achat." },
    { href: "/expertises/phygital", label: "Activation phygitale", text: "Relier magasin, digital, WhatsApp et couponing." },
    { href: "/expertises/ia-automation", label: "Automation IA retail", text: "Segmenter, relancer et piloter le lead nurturing selon le comportement client." },
    { href: "/expertises/web-si", label: "Parcours e-commerce", text: "Optimiser landing pages, tracking, catalogue et conversion." },
    { href: "/realisations#moul-pounj-world-cup", label: "Réalisation Moul Pounj", text: "Voir une campagne retail et commerce connecté." },
    { href: "/realisations/amana-tramway-phygital-2022", label: "Réalisation Amana", text: "Voir une activation phygitale tramway mesurable." },
  ],
  gms: [
    { href: "/expertises/achat-media", label: "Promotions média", text: "Booster catalogues, coupons et offres retail." },
    { href: "/expertises/brand-content", label: "Contenu social-first", text: "Rendre les mécaniques promo plus visibles avec du brand content Maroc." },
    { href: "/expertises/phygital", label: "Activation magasin", text: "Connecter rayon, QR, WhatsApp et mesure." },
    { href: "/expertises/ia-automation", label: "CRM marketing GMS", text: "Automatiser coupons, audiences, lead nurturing et conversion WhatsApp." },
    { href: "/expertises/influence", label: "Influence retail", text: "Amplifier lancements et promotions avec les bons créateurs." },
    { href: "/realisations/don-simon-back-to-school-2025", label: "Réalisation Don Simon", text: "Voir une campagne produit et réseaux sociaux." },
    { href: "/realisations#oreo-back-to-school-kv", label: "Réalisation Oreo", text: "Voir une campagne FMCG orientée visibilité." },
  ],
  institutionnel: [
    { href: "/expertises/strategie-digitale", label: "Stratégie institutionnelle", text: "Clarifier messages, publics et priorités." },
    { href: "/expertises/brand-content", label: "Contenus pédagogiques", text: "Produire des formats utiles, lisibles et mémorisables." },
    { href: "/expertises/evenementiel", label: "Événementiel", text: "Amplifier rencontres, temps forts et campagnes publiques." },
    { href: "/expertises/referencement-seo", label: "SEO / GEO", text: "Rendre les informations visibles et retrouvables." },
    { href: "/expertises/web-si", label: "Plateformes web", text: "Structurer les parcours d’information et les contenus publics." },
    { href: "/realisations#cmr-retraite-digitale", label: "Réalisation CMR", text: "Voir une campagne institutionnelle digitale." },
    { href: "/realisations#ada-produits-locaux", label: "Réalisation Agence de développement agricole", text: "Voir une prise de parole produits locaux et institutionnelle." },
  ],
  "tourisme-hotellerie": [
    { href: "/expertises/referencement-seo", label: "SEO destination", text: "Capter les recherches séjour, hôtel et expérience." },
    { href: "/expertises/brand-content", label: "Contenus immersifs", text: "Donner envie avec photos, vidéos et récits." },
    { href: "/expertises/influence", label: "Influence travel", text: "Activer les créateurs adaptés à la destination." },
    { href: "/expertises/achat-media", label: "Campagnes réservation", text: "Soutenir demandes, réservations et offres saisonnières." },
    { href: "/expertises/web-si", label: "Parcours réservation", text: "Fluidifier landing pages, tracking et demandes entrantes." },
    { href: "/realisations#ryad-al-andalous-rabat", label: "Réalisation Ryad Al Andalous", text: "Voir une référence premium liée à l’expérience et au lieu." },
  ],
  automobile: [
    { href: "/expertises/achat-media", label: "Leads & essais", text: "Générer des demandes d’essai et visites showroom." },
    { href: "/produits/whatsapp", label: "WhatsApp automobile", text: "Relancer les prospects et qualifier les demandes d’essai." },
    { href: "/expertises/ia-automation", label: "WhatsApp Business Maroc", text: "Qualifier, relancer et transmettre les leads avec automation IA." },
    { href: "/expertises/phygital", label: "Showroom connecté", text: "Relier terrain, digital et CRM commercial." },
    { href: "/expertises/web-si", label: "Landing pages essais", text: "Créer des parcours rapides pour demandes d’essai et showroom." },
    { href: "/realisations/maserati-levante-whatsapp-leads-2025", label: "Réalisation Maserati", text: "Voir l’activation WhatsApp autour de l’essai privé." },
  ],
  fmcg: [
    { href: "/expertises/brand-content", label: "Brand content Maroc", text: "Créer des KV, lancements et contenus social-first pour les marques FMCG." },
    { href: "/expertises/influence", label: "Campagne influence & UGC", text: "Amplifier les usages avec créateurs UGC et communautés." },
    { href: "/expertises/evenementiel", label: "Activation de marque", text: "Déployer des temps forts retail et expériences produits." },
    { href: "/expertises/achat-media", label: "Achat média FMCG", text: "Booster visibilité, reach, lancement produit et engagement." },
    { href: "/expertises/phygital", label: "Activation retail", text: "Connecter rayon, événement, couponing et mesure." },
    { href: "/realisations#milka-back-to-school", label: "Réalisation Milka", text: "Voir un lancement FMCG back to school." },
    { href: "/realisations/nescafe-nadi-nescafe-2019", label: "Réalisation Nescafé", text: "Voir une plateforme communautaire et phygitale." },
  ],
} satisfies Record<string, readonly SiloLink[]>;

export const sectorSiloLinksEn = {
  education: [
    { href: "/en/expertises/achat-media", label: "Admissions acquisition", text: "Generate qualified leads for schools and universities." },
    { href: "/en/expertises/seo-geo", label: "Education SEO", text: "Capture training, program and admission searches." },
    { href: "/en/expertises/ia-automation", label: "WhatsApp & CRM", text: "Follow up prospects and track registrations." },
    { href: "/en/expertises/web-si", label: "Admissions landing pages", text: "Create fast mobile journeys that convert requests." },
    { href: "/en/expertises/brand-content", label: "Proof content", text: "Reassure students and families with useful content." },
    { href: "/en/case-studies/uir-acquisition-campaign-2023-2024", label: "UIR acquisition case study", text: "See a full-funnel admissions campaign." },
    { href: "/en/case-studies/euromed-university-drupal-website-redesign-2025", label: "Euromed Drupal case study", text: "See a multilingual education web redesign." },
    { href: "/en/case-studies/tbs-master-acquisition-2025", label: "TBS Master case study", text: "See a multichannel Master acquisition campaign." },
  ],
  "real-estate": [
    { href: "/en/expertises/achat-media", label: "Real estate leads", text: "Acquire qualified requests for projects and visits." },
    { href: "/en/expertises/web-si", label: "Project landing pages", text: "Create clear journeys that convert requests." },
    { href: "/en/expertises/seo-geo", label: "Local SEO", text: "Work residence, city and neighborhood queries." },
    { href: "/en/expertises/ia-automation", label: "CRM & reporting", text: "Track leads up to the commercial visit." },
    { href: "/en/expertises/strategie-digitale", label: "Real estate digital strategy", text: "Frame audiences, proof, channels and commercial seasonality." },
    { href: "/en/case-studies/prestigia-riad-al-andalous-acquisition-2026", label: "Prestigia case study", text: "See a premium real estate acquisition campaign." },
    { href: "/en/case-studies#ryad-al-andalous-rabat", label: "Ryad Al Andalous case", text: "See a premium real estate reference." },
    { href: "/en/case-studies#rabat-riviera-golf-living", label: "Rabat Riviera case", text: "See a real estate and lifestyle campaign." },
  ],
  "retail-ecommerce": [
    { href: "/en/expertises/achat-media", label: "Drive-to-store", text: "Generate traffic, sales and store visits." },
    { href: "/en/expertises/brand-content", label: "Social commerce", text: "Produce content that triggers purchase." },
    { href: "/en/expertises/phygital", label: "Phygital activation", text: "Connect store, digital, WhatsApp and couponing." },
    { href: "/en/expertises/ia-automation", label: "Retail AI automation", text: "Segment, follow up and manage lead nurturing based on customer behavior." },
    { href: "/en/expertises/web-si", label: "E-commerce journeys", text: "Optimize landing pages, tracking, catalogue and conversion." },
    { href: "/en/case-studies#moul-pounj-world-cup", label: "Moul Pounj case", text: "See a retail and connected commerce campaign." },
    { href: "/en/case-studies/amana-tramway-phygital-2022", label: "Amana case", text: "See a measurable tramway phygital activation." },
  ],
  "grocery-retail": [
    { href: "/en/expertises/achat-media", label: "Retail promotions", text: "Boost catalogues, coupons and offers." },
    { href: "/en/expertises/brand-content", label: "Social-first content", text: "Make promotional mechanics more visible with brand content in Morocco." },
    { href: "/en/expertises/phygital", label: "In-store activation", text: "Connect shelves, QR, WhatsApp and measurement." },
    { href: "/en/expertises/ia-automation", label: "Grocery retail marketing CRM", text: "Automate coupons, audiences, lead nurturing and WhatsApp conversion." },
    { href: "/en/expertises/influence", label: "Retail influence", text: "Amplify launches and promotions with the right creators." },
    { href: "/en/case-studies/don-simon-back-to-school-2025", label: "Don Simon case", text: "See a product and social media campaign." },
    { href: "/en/case-studies#oreo-back-to-school-kv", label: "Oreo case", text: "See an FMCG visibility campaign." },
  ],
  institutional: [
    { href: "/en/expertises/strategie-digitale", label: "Institutional strategy", text: "Clarify messages, audiences and priorities." },
    { href: "/en/expertises/brand-content", label: "Educational content", text: "Produce useful, readable and memorable formats." },
    { href: "/en/expertises/evenementiel", label: "Events", text: "Amplify meetings, key moments and public campaigns." },
    { href: "/en/expertises/seo-geo", label: "SEO / GEO", text: "Make information visible and discoverable." },
    { href: "/en/expertises/web-si", label: "Web platforms", text: "Structure public information journeys and content." },
    { href: "/en/case-studies#cmr-retraite-digitale", label: "CMR case", text: "See a digital institutional campaign." },
    { href: "/en/case-studies#ada-produits-locaux", label: "Agence de développement agricole case", text: "See a local products and institutional narrative." },
  ],
  "tourism-hospitality": [
    { href: "/en/expertises/seo-geo", label: "Destination SEO", text: "Capture stay, hotel and experience searches." },
    { href: "/en/expertises/brand-content", label: "Immersive content", text: "Create desire with photos, videos and stories." },
    { href: "/en/expertises/influence", label: "Travel influence", text: "Activate creators suited to the destination." },
    { href: "/en/expertises/achat-media", label: "Booking campaigns", text: "Support requests, bookings and seasonal offers." },
    { href: "/en/expertises/web-si", label: "Booking journeys", text: "Improve landing pages, tracking and inbound requests." },
    { href: "/en/case-studies#ryad-al-andalous-rabat", label: "Ryad Al Andalous case", text: "See a premium reference linked to place and experience." },
  ],
  automotive: [
    { href: "/en/expertises/achat-media", label: "Leads & test drives", text: "Generate test-drive requests and showroom visits." },
    { href: "/en/products/whatsapp", label: "Automotive WhatsApp", text: "Follow up prospects and qualify test-drive requests." },
    { href: "/en/expertises/ia-automation", label: "WhatsApp Business Morocco", text: "Qualify, follow up and route leads with AI automation." },
    { href: "/en/expertises/phygital", label: "Connected showroom", text: "Link field, digital and commercial CRM." },
    { href: "/en/expertises/web-si", label: "Test-drive landing pages", text: "Create fast journeys for test-drive and showroom requests." },
    { href: "/en/case-studies/maserati-levante-whatsapp-leads-2025", label: "Maserati case", text: "See the WhatsApp activation around the private test drive." },
  ],
  fmcg: [
    { href: "/en/expertises/brand-content", label: "Brand content in Morocco", text: "Create key visuals, launches and social-first content for FMCG brands." },
    { href: "/en/expertises/influence", label: "Influence campaign & UGC", text: "Amplify use cases with UGC creators and communities." },
    { href: "/en/expertises/evenementiel", label: "Brand activation", text: "Deploy retail and experience-driven product moments." },
    { href: "/en/expertises/achat-media", label: "FMCG media buying", text: "Boost visibility, reach, product launches and engagement." },
    { href: "/en/expertises/phygital", label: "Retail activation", text: "Connect shelves, events, couponing and measurement." },
    { href: "/en/case-studies#milka-back-to-school", label: "Milka case", text: "See a back-to-school FMCG launch." },
    { href: "/en/case-studies/nescafe-nadi-nescafe-2019", label: "Nescafé case", text: "See a community and phygital platform." },
  ],
} satisfies Record<string, readonly SiloLink[]>;

export const proofCaseLinksFr = [
  {
    client: "Maserati",
    campaign: "Push WhatsApp - essai privé Levante",
    category: "Automobile",
    links: [
      { href: "/realisations/maserati-levante-whatsapp-leads-2025", label: "Réalisation Richmedia", text: "Voir le case study Maserati Levante." },
      { href: "/secteurs/automobile", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur automobile." },
      { href: "/expertises/ia-automation", label: "Dispositif de croissance", text: "Approfondir WhatsApp, CRM et automation IA." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une activation WhatsApp similaire." },
    ],
  },
  {
    client: "Chergui",
    campaign: "Conception et emballage",
    category: "FMCG",
    links: [
      { href: "#chergui-conception-emballage", label: "Réalisation Richmedia", text: "Repérer la référence Chergui dans la page." },
      { href: "/secteurs/fmcg", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur FMCG." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir brand content, packaging et contenu social-first." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne produit ou packaging." },
    ],
  },
  {
    client: "Oreo",
    campaign: "KV Campagne Back to School",
    category: "FMCG",
    links: [
      { href: "#oreo-back-to-school-kv", label: "Réalisation Richmedia", text: "Repérer la référence Oreo dans la page." },
      { href: "/secteurs/fmcg", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur FMCG." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir KV, lancement et activation de marque." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne back to school." },
    ],
  },
  {
    client: "Nescafé",
    campaign: "Campagne Nadi Nescafé",
    category: "FMCG",
    links: [
      { href: "/realisations/nescafe-nadi-nescafe-2019", label: "Réalisation Richmedia", text: "Lire le cas client Nadi Nescafé complet." },
      { href: "/secteurs/fmcg", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur FMCG." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir activation de marque et contenu social-first." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une activation personnalisée." },
    ],
  },
  {
    client: "Milka",
    campaign: "KV et lancement de campagne Back to school",
    category: "FMCG",
    links: [
      { href: "#milka-back-to-school", label: "Réalisation Richmedia", text: "Repérer la référence Milka dans la page." },
      { href: "/secteurs/fmcg", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur FMCG." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir KV, lancement produit et social-first." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne FMCG." },
    ],
  },
  {
    client: "UIR",
    campaign: "Campagnes digitales",
    category: "Éducation",
    links: [
      { href: "/realisations/uir-campagne-acquisition-2023-2024", label: "Cas client marketing digital", text: "Lire le cas client UIR acquisition complet." },
      { href: "/secteurs/education", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur éducation." },
      { href: "/expertises/achat-media", label: "Dispositif de croissance", text: "Approfondir acquisition, média et admissions." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne admissions." },
    ],
  },
  {
    client: "Amana",
    campaign: "Tramway wrapping",
    category: "Retail & mobilité",
    links: [
      { href: "/realisations/amana-tramway-phygital-2022", label: "Réalisation Richmedia", text: "Lire le cas client Amana phygital complet." },
      { href: "/secteurs/retail-ecommerce", label: "Campagne digitale au Maroc", text: "Relier ce cas au retail et commerce connecté." },
      { href: "/expertises/phygital", label: "Dispositif de croissance", text: "Approfondir activation phygitale et visibilité terrain." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une activation retail." },
    ],
  },
  {
    client: "Amana",
    campaign: "20th anniversary",
    category: "Brand content",
    links: [
      { href: "#amana-20th-anniversary", label: "Réalisation Richmedia", text: "Repérer la référence Amana anniversaire." },
      { href: "/secteurs/retail-ecommerce", label: "Campagne digitale au Maroc", text: "Relier ce cas au retail et à la marque." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir contenu de marque et activation." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une prise de parole de marque." },
    ],
  },
  {
    client: "Don Simon",
    campaign: "Product photoshoot",
    category: "FMCG",
    links: [
      { href: "/realisations/don-simon-back-to-school-2025", label: "Réalisation Richmedia", text: "Voir le case study Don Simon Back to School." },
      { href: "/secteurs/fmcg", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur FMCG." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir contenus produits et social-first." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne produit." },
    ],
  },
  {
    client: "Agence de développement agricole",
    campaign: "Produits locaux",
    category: "Institutionnel",
    links: [
      { href: "#ada-produits-locaux", label: "Réalisation Richmedia", text: "Repérer la référence Agence de développement agricole dans la page." },
      { href: "/secteurs/institutionnel", label: "Campagne digitale au Maroc", text: "Relier ce cas aux campagnes institutionnelles." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir narration, contenu et pédagogie." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne publique ou produit local." },
    ],
  },
  {
    client: "Ryad Al Andalous",
    campaign: "Rabat",
    category: "Immobilier",
    links: [
      { href: "#ryad-al-andalous-rabat", label: "Réalisation Richmedia", text: "Repérer la référence Ryad Al Andalous." },
      { href: "/secteurs/immobilier", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur immobilier." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir contenu premium et preuve de marque." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne immobilière." },
    ],
  },
  {
    client: "Tramway Rabat",
    campaign: "Summer",
    category: "Mobilité",
    links: [
      { href: "/realisations/tramway-rabat-sale-community-management-2026", label: "Réalisation Richmedia", text: "Lire le cas client Tramway Social Media complet." },
      { href: "/secteurs/institutionnel", label: "Campagne digitale au Maroc", text: "Relier ce cas aux campagnes publiques et mobilité." },
      { href: "/expertises/social-media-maroc", label: "Dispositif de croissance", text: "Approfondir social media, community management et social care." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une activation mobilité." },
    ],
  },
  {
    client: "Moul Pounj",
    campaign: "World Cup",
    category: "Retail",
    links: [
      { href: "#moul-pounj-world-cup", label: "Réalisation Richmedia", text: "Repérer la référence Moul Pounj." },
      { href: "/secteurs/retail-ecommerce", label: "Campagne digitale au Maroc", text: "Relier ce cas au retail et e-commerce." },
      { href: "/expertises/phygital", label: "Dispositif de croissance", text: "Approfondir activation retail et commerce connecté." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne retail." },
    ],
  },
  {
    client: "TBS Education",
    campaign: "Master Casablanca",
    category: "Éducation",
    links: [
      { href: "/realisations/tbs-master-acquisition-2025", label: "Réalisation Richmedia", text: "Lire le cas client TBS Master complet." },
      { href: "/secteurs/education", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur éducation." },
      { href: "/expertises/achat-media", label: "Dispositif de croissance", text: "Approfondir acquisition, média et inscriptions." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne formation." },
    ],
  },
  {
    client: "CMR",
    campaign: "Retraite digitale",
    category: "Institutionnel",
    links: [
      { href: "#cmr-retraite-digitale", label: "Réalisation Richmedia", text: "Repérer la référence CMR." },
      { href: "/secteurs/institutionnel", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur institutionnel." },
      { href: "/expertises/strategie-digitale", label: "Dispositif de croissance", text: "Approfondir stratégie, pédagogie et canaux." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne institutionnelle." },
    ],
  },
  {
    client: "Rabat Riviera",
    campaign: "Golf living",
    category: "Immobilier",
    links: [
      { href: "#rabat-riviera-golf-living", label: "Réalisation Richmedia", text: "Repérer la référence Rabat Riviera." },
      { href: "/secteurs/immobilier", label: "Campagne digitale au Maroc", text: "Relier ce cas au secteur immobilier." },
      { href: "/expertises/achat-media", label: "Dispositif de croissance", text: "Approfondir acquisition et génération de leads." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une campagne immobilière." },
    ],
  },
  {
    client: "BED",
    campaign: "Brand identity",
    category: "Brand content",
    links: [
      { href: "#beed-brand-identity", label: "Réalisation Richmedia", text: "Repérer la référence BED." },
      { href: "/secteurs/institutionnel", label: "Campagne digitale au Maroc", text: "Relier ce cas à la marque et aux services." },
      { href: "/expertises/brand-content", label: "Dispositif de croissance", text: "Approfondir identité, contenu et activation." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer une identité ou campagne de marque." },
    ],
  },
  {
    client: "Tramway Rabat",
    campaign: "Mobile app",
    category: "Mobilité",
    links: [
      { href: "#tramway-rabat-mobile-app", label: "Réalisation Richmedia", text: "Repérer la référence app Tramway." },
      { href: "/secteurs/institutionnel", label: "Campagne digitale au Maroc", text: "Relier ce cas aux services publics et mobilité." },
      { href: "/expertises/web-si", label: "Dispositif de croissance", text: "Approfondir web, SI, parcours et plateformes." },
      { href: "/contact", label: "Créer un dispositif de croissance", text: "Cadrer un projet web ou applicatif." },
    ],
  },
] satisfies readonly ProofCaseLinkSet[];

export const proofCaseLinksEn = [
  {
    client: "Maserati",
    campaign: "WhatsApp push - private Levante test drive",
    category: "Automotive",
    links: [
      { href: "/en/case-studies/maserati-levante-whatsapp-leads-2025", label: "Richmedia case study", text: "Open the Maserati Levante case study." },
      { href: "/en/sectors/automotive", label: "Digital campaign in Morocco", text: "Connect this case to the automotive sector." },
      { href: "/en/expertises/ia-automation", label: "Growth system", text: "Explore WhatsApp, CRM and AI automation." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a similar WhatsApp activation." },
    ],
  },
  {
    client: "Chergui",
    campaign: "Design and packaging",
    category: "FMCG",
    links: [
      { href: "#chergui-conception-emballage", label: "Richmedia case study", text: "Find the Chergui reference on this page." },
      { href: "/en/sectors/fmcg", label: "Digital campaign in Morocco", text: "Connect this case to FMCG." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore brand content, packaging and social-first content." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a product or packaging campaign." },
    ],
  },
  {
    client: "Oreo",
    campaign: "Back to School campaign KV",
    category: "FMCG",
    links: [
      { href: "#oreo-back-to-school-kv", label: "Richmedia case study", text: "Find the Oreo reference on this page." },
      { href: "/en/sectors/fmcg", label: "Digital campaign in Morocco", text: "Connect this case to FMCG." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore key visuals, launch and brand activation." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a back-to-school campaign." },
    ],
  },
  {
    client: "Nescafé",
    campaign: "Nadi Nescafé campaign",
    category: "FMCG",
    links: [
      { href: "/en/case-studies/nescafe-nadi-nescafe-2019", label: "Richmedia case study", text: "Open the full Nadi Nescafé case study." },
      { href: "/en/sectors/fmcg", label: "Digital campaign in Morocco", text: "Connect this case to FMCG." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore brand activation and social-first content." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a personalized activation." },
    ],
  },
  {
    client: "Milka",
    campaign: "Back to School campaign launch and KV",
    category: "FMCG",
    links: [
      { href: "#milka-back-to-school", label: "Richmedia case study", text: "Find the Milka reference on this page." },
      { href: "/en/sectors/fmcg", label: "Digital campaign in Morocco", text: "Connect this case to FMCG." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore product launch and social-first content." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame an FMCG campaign." },
    ],
  },
  {
    client: "UIR",
    campaign: "Digital campaigns",
    category: "Education",
    links: [
      { href: "/en/case-studies/uir-acquisition-campaign-2023-2024", label: "Digital marketing case study", text: "Read the full UIR acquisition case study." },
      { href: "/en/sectors/education", label: "Digital campaign in Morocco", text: "Connect this case to education." },
      { href: "/en/expertises/achat-media", label: "Growth system", text: "Explore acquisition, media and admissions." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame an admissions campaign." },
    ],
  },
  {
    client: "Amana",
    campaign: "Tramway wrapping",
    category: "Retail & mobility",
    links: [
      { href: "/en/case-studies/amana-tramway-phygital-2022", label: "Richmedia case study", text: "Open the full Amana phygital case study." },
      { href: "/en/sectors/retail-ecommerce", label: "Digital campaign in Morocco", text: "Connect this case to retail and connected commerce." },
      { href: "/en/expertises/phygital", label: "Growth system", text: "Explore phygital activation and field visibility." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a retail activation." },
    ],
  },
  {
    client: "Amana",
    campaign: "20th anniversary",
    category: "Brand content",
    links: [
      { href: "#amana-20th-anniversary", label: "Richmedia case study", text: "Find the Amana anniversary reference." },
      { href: "/en/sectors/retail-ecommerce", label: "Digital campaign in Morocco", text: "Connect this case to retail and brand." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore brand content and activation." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a brand narrative." },
    ],
  },
  {
    client: "Don Simon",
    campaign: "Product photoshoot",
    category: "FMCG",
    links: [
      { href: "/en/case-studies/don-simon-back-to-school-2025", label: "Richmedia case study", text: "Open the Don Simon Back to School case study." },
      { href: "/en/sectors/fmcg", label: "Digital campaign in Morocco", text: "Connect this case to FMCG." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore product content and social-first creative." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a product campaign." },
    ],
  },
  {
    client: "Agence de développement agricole",
    campaign: "Local products",
    category: "Institutional",
    links: [
      { href: "#ada-produits-locaux", label: "Richmedia case study", text: "Find the Agence de développement agricole reference on this page." },
      { href: "/en/sectors/institutional", label: "Digital campaign in Morocco", text: "Connect this case to institutional campaigns." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore narrative, content and education." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a public or local-product campaign." },
    ],
  },
  {
    client: "Ryad Al Andalous",
    campaign: "Rabat",
    category: "Real estate",
    links: [
      { href: "#ryad-al-andalous-rabat", label: "Richmedia case study", text: "Find the Ryad Al Andalous reference." },
      { href: "/en/sectors/real-estate", label: "Digital campaign in Morocco", text: "Connect this case to real estate." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore premium content and brand proof." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a real estate campaign." },
    ],
  },
  {
    client: "Tramway Rabat",
    campaign: "Summer",
    category: "Mobility",
    links: [
      { href: "/en/case-studies/tramway-rabat-sale-community-management-2026", label: "Richmedia case study", text: "Open the full Tramway Social Media case study." },
      { href: "/en/sectors/institutional", label: "Digital campaign in Morocco", text: "Connect this case to public and mobility campaigns." },
      { href: "/en/expertises/social-media-morocco", label: "Growth system", text: "Explore social media, community management and social care." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a mobility activation." },
    ],
  },
  {
    client: "Moul Pounj",
    campaign: "World Cup",
    category: "Retail",
    links: [
      { href: "#moul-pounj-world-cup", label: "Richmedia case study", text: "Find the Moul Pounj reference." },
      { href: "/en/sectors/retail-ecommerce", label: "Digital campaign in Morocco", text: "Connect this case to retail and e-commerce." },
      { href: "/en/expertises/phygital", label: "Growth system", text: "Explore retail activation and connected commerce." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a retail campaign." },
    ],
  },
  {
    client: "TBS Education",
    campaign: "Casablanca Master",
    category: "Education",
    links: [
      { href: "/en/case-studies/tbs-master-acquisition-2025", label: "Richmedia case study", text: "Open the full TBS Master case study." },
      { href: "/en/sectors/education", label: "Digital campaign in Morocco", text: "Connect this case to education." },
      { href: "/en/expertises/achat-media", label: "Growth system", text: "Explore acquisition, media and registrations." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a training campaign." },
    ],
  },
  {
    client: "CMR",
    campaign: "Digital retirement",
    category: "Institutional",
    links: [
      { href: "#cmr-retraite-digitale", label: "Richmedia case study", text: "Find the CMR reference." },
      { href: "/en/sectors/institutional", label: "Digital campaign in Morocco", text: "Connect this case to institutional work." },
      { href: "/en/expertises/strategie-digitale", label: "Growth system", text: "Explore strategy, education and channel planning." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame an institutional campaign." },
    ],
  },
  {
    client: "Rabat Riviera",
    campaign: "Golf living",
    category: "Real estate",
    links: [
      { href: "#rabat-riviera-golf-living", label: "Richmedia case study", text: "Find the Rabat Riviera reference." },
      { href: "/en/sectors/real-estate", label: "Digital campaign in Morocco", text: "Connect this case to real estate." },
      { href: "/en/expertises/achat-media", label: "Growth system", text: "Explore acquisition and lead generation." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a real estate campaign." },
    ],
  },
  {
    client: "BED",
    campaign: "Brand identity",
    category: "Brand content",
    links: [
      { href: "#beed-brand-identity", label: "Richmedia case study", text: "Find the BED reference." },
      { href: "/en/sectors/institutional", label: "Digital campaign in Morocco", text: "Connect this case to brand and services." },
      { href: "/en/expertises/brand-content", label: "Growth system", text: "Explore identity, content and activation." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a brand identity or campaign." },
    ],
  },
  {
    client: "Tramway Rabat",
    campaign: "Mobile app",
    category: "Mobility",
    links: [
      { href: "#tramway-rabat-mobile-app", label: "Richmedia case study", text: "Find the Tramway app reference." },
      { href: "/en/sectors/institutional", label: "Digital campaign in Morocco", text: "Connect this case to public services and mobility." },
      { href: "/en/expertises/web-si", label: "Growth system", text: "Explore web, systems, journeys and platforms." },
      { href: "/en/contact", label: "Create a growth system", text: "Frame a web or app project." },
    ],
  },
] satisfies readonly ProofCaseLinkSet[];
